//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.App_GlobalResources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для учетной  записи:.
        /// </summary>
        public static string error_ad_text1 {
            get {
                return ResourceManager.GetString("error_ad_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на доступ запрещен к ресурсу.
        /// </summary>
        public static string error_ad_text2 {
            get {
                return ResourceManager.GetString("error_ad_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Извините что-то пошло не так..
        /// </summary>
        public static string error_message {
            get {
                return ResourceManager.GetString("error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АрселорМиттал Кривой Рог.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить доступ.
        /// </summary>
        public static string home_access {
            get {
                return ResourceManager.GetString("home_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RFID-Карты.
        /// </summary>
        public static string home_cards {
            get {
                return ResourceManager.GetString("home_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RFID-Карты (Администрирование).
        /// </summary>
        public static string home_cards_adm {
            get {
                return ResourceManager.GetString("home_cards_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суточный отчет (АЗС).
        /// </summary>
        public static string home_daili_report_azs {
            get {
                return ResourceManager.GetString("home_daili_report_azs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суточный отчет (экипировка ст. &quot;Карьерная ГД&quot;).
        /// </summary>
        public static string home_daili_report_rw {
            get {
                return ResourceManager.GetString("home_daili_report_rw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заправочная ведомость.
        /// </summary>
        public static string home_fuel_sales {
            get {
                return ResourceManager.GetString("home_fuel_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заправочная ведомость ж.д. транспорта ГД.
        /// </summary>
        public static string home_fuel_sales_rw {
            get {
                return ResourceManager.GetString("home_fuel_sales_rw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суточный отчет.
        /// </summary>
        public static string home_link_dailireport_azs {
            get {
                return ResourceManager.GetString("home_link_dailireport_azs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суточный отчет.
        /// </summary>
        public static string home_link_dailireport_kgd {
            get {
                return ResourceManager.GetString("home_link_dailireport_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суточный отчет (АЗС).
        /// </summary>
        public static string home_link_description_dailireport_azs {
            get {
                return ResourceManager.GetString("home_link_description_dailireport_azs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суточный отчет (экипировка ст. &quot;Карьерная ГД&quot;).
        /// </summary>
        public static string home_link_description_dailireport_kgd {
            get {
                return ResourceManager.GetString("home_link_description_dailireport_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация.
        /// </summary>
        public static string home_link_description_fuel_azs {
            get {
                return ResourceManager.GetString("home_link_description_fuel_azs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация.
        /// </summary>
        public static string home_link_description_fuel_gd {
            get {
                return ResourceManager.GetString("home_link_description_fuel_gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заправочная ведомость (по объему и весу).
        /// </summary>
        public static string home_link_description_fuelsales {
            get {
                return ResourceManager.GetString("home_link_description_fuelsales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заправочная ведомость (по объему и весу).
        /// </summary>
        public static string home_link_description_fuelsales_kgd {
            get {
                return ResourceManager.GetString("home_link_description_fuelsales_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчетная документация.
        /// </summary>
        public static string home_link_description_oil {
            get {
                return ResourceManager.GetString("home_link_description_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступления масла на ЦСМ.
        /// </summary>
        public static string home_link_description_oilreceipt {
            get {
                return ResourceManager.GetString("home_link_description_oilreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвентаризация остатков на ЦСМ.
        /// </summary>
        public static string home_link_description_oilresidue {
            get {
                return ResourceManager.GetString("home_link_description_oilresidue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выдача масла из ЦСМ.
        /// </summary>
        public static string home_link_description_oilsales {
            get {
                return ResourceManager.GetString("home_link_description_oilsales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перекачка масла на ЦСМ.
        /// </summary>
        public static string home_link_description_oiltransfer {
            get {
                return ResourceManager.GetString("home_link_description_oiltransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомость приема топлива (экипировка ж.д. ГД).
        /// </summary>
        public static string home_link_description_receiving_fuel_kgd {
            get {
                return ResourceManager.GetString("home_link_description_receiving_fuel_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки диз. топлива в емкостях ст. Карьерная.
        /// </summary>
        public static string home_link_description_remainstanks_kgd {
            get {
                return ResourceManager.GetString("home_link_description_remainstanks_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список RFID-карт установленных на АМКР.
        /// </summary>
        public static string home_link_description_RFID_cards {
            get {
                return ResourceManager.GetString("home_link_description_RFID_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние склада ГСМ.
        /// </summary>
        public static string home_link_description_tankstates {
            get {
                return ResourceManager.GetString("home_link_description_tankstates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экипировка станции &quot;Карьерная ГД&quot;.
        /// </summary>
        public static string home_link_description_tankstates_kgd {
            get {
                return ResourceManager.GetString("home_link_description_tankstates_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АЗС АМКР.
        /// </summary>
        public static string home_link_fuel_azs {
            get {
                return ResourceManager.GetString("home_link_fuel_azs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экипировка &quot;Карьерная&quot; АМКР.
        /// </summary>
        public static string home_link_fuel_gd {
            get {
                return ResourceManager.GetString("home_link_fuel_gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выдача ГСМ.
        /// </summary>
        public static string home_link_fuelsales {
            get {
                return ResourceManager.GetString("home_link_fuelsales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выдача ж.д. ГД.
        /// </summary>
        public static string home_link_fuelsales_kgd {
            get {
                return ResourceManager.GetString("home_link_fuelsales_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЦСМ АМКР.
        /// </summary>
        public static string home_link_oil {
            get {
                return ResourceManager.GetString("home_link_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поступления.
        /// </summary>
        public static string home_link_oilreceipt {
            get {
                return ResourceManager.GetString("home_link_oilreceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки.
        /// </summary>
        public static string home_link_oilresidue {
            get {
                return ResourceManager.GetString("home_link_oilresidue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выдача.
        /// </summary>
        public static string home_link_oilsales {
            get {
                return ResourceManager.GetString("home_link_oilsales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перекачки.
        /// </summary>
        public static string home_link_oiltransfer {
            get {
                return ResourceManager.GetString("home_link_oiltransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием ж.д. ГД.
        /// </summary>
        public static string home_link_receiving_fuel_kgd {
            get {
                return ResourceManager.GetString("home_link_receiving_fuel_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки.
        /// </summary>
        public static string home_link_remainstanks_kgd {
            get {
                return ResourceManager.GetString("home_link_remainstanks_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RFID-Карты.
        /// </summary>
        public static string home_link_RFID_cards {
            get {
                return ResourceManager.GetString("home_link_RFID_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RFID-Карты (Администрирование).
        /// </summary>
        public static string home_link_RFID_cards_adm {
            get {
                return ResourceManager.GetString("home_link_RFID_cards_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГСМ АЗС.
        /// </summary>
        public static string home_link_tankstates {
            get {
                return ResourceManager.GetString("home_link_tankstates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экипировка локомотивов.
        /// </summary>
        public static string home_link_tankstates_kgd {
            get {
                return ResourceManager.GetString("home_link_tankstates_kgd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная информация.
        /// </summary>
        public static string home_more_link {
            get {
                return ResourceManager.GetString("home_more_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопросы по электронной почте.
        /// </summary>
        public static string home_questions_email {
            get {
                return ResourceManager.GetString("home_questions_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведомость приема топлива (экипировка ж.д. транспорта ГД).
        /// </summary>
        public static string home_receiving_fuel_rw {
            get {
                return ResourceManager.GetString("home_receiving_fuel_rw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки в емкостях.
        /// </summary>
        public static string home_remains_tanks_oil {
            get {
                return ResourceManager.GetString("home_remains_tanks_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остатки в емкостях.
        /// </summary>
        public static string home_remains_tanks_rw {
            get {
                return ResourceManager.GetString("home_remains_tanks_rw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние склада ГСМ АЗС.
        /// </summary>
        public static string home_tank_states {
            get {
                return ResourceManager.GetString("home_tank_states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экипировка ст. &quot;Карьерная ГД&quot;.
        /// </summary>
        public static string home_tank_states_rw {
            get {
                return ResourceManager.GetString("home_tank_states_rw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система контроля топлива.
        /// </summary>
        public static string home_title {
            get {
                return ResourceManager.GetString("home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система контроля ЦСМ.
        /// </summary>
        public static string home_title_oil {
            get {
                return ResourceManager.GetString("home_title_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перекачка масла на ЦСМ.
        /// </summary>
        public static string home_transfer_oil {
            get {
                return ResourceManager.GetString("home_transfer_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню АЗС.
        /// </summary>
        public static string link_menu_home_fuel_azs {
            get {
                return ResourceManager.GetString("link_menu_home_fuel_azs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню АЗС ГД.
        /// </summary>
        public static string link_menu_home_fuel_gd {
            get {
                return ResourceManager.GetString("link_menu_home_fuel_gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню ЦСМ.
        /// </summary>
        public static string link_menu_home_oil {
            get {
                return ResourceManager.GetString("link_menu_home_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mailto:KRR.IT.Service@arcelormittal.com.
        /// </summary>
        public static string mail_access {
            get {
                return ResourceManager.GetString("mail_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещен.
        /// </summary>
        public static string title_access_denied {
            get {
                return ResourceManager.GetString("title_access_denied", resourceCulture);
            }
        }
    }
}
