//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("DECLAR", Namespace = "", IsNullable = false)]
public partial class DeclarContent
{

    private DHead dECLARHEADField;

    private DBody dECLARBODYField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DHead DECLARHEAD
    {
        get
        {
            return this.dECLARHEADField;
        }
        set
        {
            this.dECLARHEADField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DBody DECLARBODY
    {
        get
        {
            return this.dECLARBODYField;
        }
        set
        {
            this.dECLARBODYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DHead
{

    private string tINField;

    private string c_DOCField;

    private string c_DOC_SUBField;

    private string c_DOC_VERField;

    private string c_DOC_TYPEField;

    private string c_DOC_CNTField;

    private string c_REGField;

    private string c_RAJField;

    private string pERIOD_MONTHField;

    private string pERIOD_TYPEField;

    private string pERIOD_YEARField;

    private string c_STI_ORIGField;

    private string c_DOC_STANField;

    private DHeadDOC[] lINKED_DOCSField;

    private string d_FILLField;

    private string sOFTWAREField;

    public DHead()
    {
        this.c_DOCField = "J02";
        this.c_DOC_SUBField = "104";
        this.c_DOC_VERField = "1";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TIN
    {
        get
        {
            return this.tINField;
        }
        set
        {
            this.tINField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string C_DOC
    {
        get
        {
            return this.c_DOCField;
        }
        set
        {
            this.c_DOCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string C_DOC_SUB
    {
        get
        {
            return this.c_DOC_SUBField;
        }
        set
        {
            this.c_DOC_SUBField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string C_DOC_VER
    {
        get
        {
            return this.c_DOC_VERField;
        }
        set
        {
            this.c_DOC_VERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "nonNegativeInteger")]
    public string C_DOC_TYPE
    {
        get
        {
            return this.c_DOC_TYPEField;
        }
        set
        {
            this.c_DOC_TYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "nonNegativeInteger")]
    public string C_DOC_CNT
    {
        get
        {
            return this.c_DOC_CNTField;
        }
        set
        {
            this.c_DOC_CNTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string C_REG
    {
        get
        {
            return this.c_REGField;
        }
        set
        {
            this.c_REGField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string C_RAJ
    {
        get
        {
            return this.c_RAJField;
        }
        set
        {
            this.c_RAJField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string PERIOD_MONTH
    {
        get
        {
            return this.pERIOD_MONTHField;
        }
        set
        {
            this.pERIOD_MONTHField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string PERIOD_TYPE
    {
        get
        {
            return this.pERIOD_TYPEField;
        }
        set
        {
            this.pERIOD_TYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string PERIOD_YEAR
    {
        get
        {
            return this.pERIOD_YEARField;
        }
        set
        {
            this.pERIOD_YEARField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string C_STI_ORIG
    {
        get
        {
            return this.c_STI_ORIGField;
        }
        set
        {
            this.c_STI_ORIGField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string C_DOC_STAN
    {
        get
        {
            return this.c_DOC_STANField;
        }
        set
        {
            this.c_DOC_STANField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DOC", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public DHeadDOC[] LINKED_DOCS
    {
        get
        {
            return this.lINKED_DOCSField;
        }
        set
        {
            this.lINKED_DOCSField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string D_FILL
    {
        get
        {
            return this.d_FILLField;
        }
        set
        {
            this.d_FILLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public string SOFTWARE
    {
        get
        {
            return this.sOFTWAREField;
        }
        set
        {
            this.sOFTWAREField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class DHeadDOC
{

    private string c_DOCField;

    private string c_DOC_SUBField;

    private string c_DOC_VERField;

    private string c_DOC_TYPEField;

    private string c_DOC_CNTField;

    private string c_DOC_STANField;

    private string fILENAMEField;

    private string nUMField;

    private string tYPEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string C_DOC
    {
        get
        {
            return this.c_DOCField;
        }
        set
        {
            this.c_DOCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string C_DOC_SUB
    {
        get
        {
            return this.c_DOC_SUBField;
        }
        set
        {
            this.c_DOC_SUBField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string C_DOC_VER
    {
        get
        {
            return this.c_DOC_VERField;
        }
        set
        {
            this.c_DOC_VERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "nonNegativeInteger")]
    public string C_DOC_TYPE
    {
        get
        {
            return this.c_DOC_TYPEField;
        }
        set
        {
            this.c_DOC_TYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "nonNegativeInteger")]
    public string C_DOC_CNT
    {
        get
        {
            return this.c_DOC_CNTField;
        }
        set
        {
            this.c_DOC_CNTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
    public string C_DOC_STAN
    {
        get
        {
            return this.c_DOC_STANField;
        }
        set
        {
            this.c_DOC_STANField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FILENAME
    {
        get
        {
            return this.fILENAMEField;
        }
        set
        {
            this.fILENAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string NUM
    {
        get
        {
            return this.nUMField;
        }
        set
        {
            this.nUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string TYPE
    {
        get
        {
            return this.tYPEField;
        }
        set
        {
            this.tYPEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Ozn2Column
{

    private int rOWNUMField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ROWNUM
    {
        get
        {
            return this.rOWNUMField;
        }
        set
        {
            this.rOWNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Decimal2Column
{

    private int rOWNUMField;

    private decimal valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ROWNUM
    {
        get
        {
            return this.rOWNUMField;
        }
        set
        {
            this.rOWNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChkColumn
{

    private int rOWNUMField;

    private int valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ROWNUM
    {
        get
        {
            return this.rOWNUMField;
        }
        set
        {
            this.rOWNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public int Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StrColumn
{

    private int rOWNUMField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ROWNUM
    {
        get
        {
            return this.rOWNUMField;
        }
        set
        {
            this.rOWNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class KOATUUColumn
{

    private int rOWNUMField;

    private ulong valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ROWNUM
    {
        get
        {
            return this.rOWNUMField;
        }
        set
        {
            this.rOWNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public ulong Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DGI4nomColumn
{

    private int rOWNUMField;

    private ulong valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ROWNUM
    {
        get
        {
            return this.rOWNUMField;
        }
        set
        {
            this.rOWNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public ulong Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DBody
{

    private int itemField;

    private ItemChoiceType itemElementNameField;

    //private string hDATEField;

    private string hNUMField;

    private string hDATE1Field;

    private string hTIME1Field;

    private string hDATE2Field;

    private string hTIME2Field;

    private string hNUMREGField;

    private string hTINField;

    private string hNAMEField;

    private string r07G1Field;

    private DGI4nomColumn[] t1RXXXXG1Field;

    private KOATUUColumn[] t1RXXXXG2Field;

    private StrColumn[] t1RXXXXG3SField;

    private ChkColumn[] t1RXXXXG4Field;

    private StrColumn[] t1RXXXXG5SField;

    private StrColumn[] t1RXXXXG6SField;

    private Decimal2Column[] t1RXXXXG7Field;

    private Decimal2Column[] t1RXXXXG8Field;

    private Decimal2Column[] t1RXXXXG9Field;

    private Decimal2Column[] t1RXXXXG10Field;

    private Ozn2Column[] t1RXXXXG11Field;

    private DGI4nomColumn[] t2RXXXXG1Field;

    private KOATUUColumn[] t2RXXXXG2Field;

    private StrColumn[] t2RXXXXG3SField;

    private Decimal2Column[] t2RXXXXG4Field;

    private Decimal2Column[] t2RXXXXG5Field;

    private Ozn2Column[] t2RXXXXG6Field;

    private DGI4nomColumn[] t3RXXXXG1Field;

    private KOATUUColumn[] t3RXXXXG2Field;

    private StrColumn[] t3RXXXXG3SField;

    private StrColumn[] t3RXXXXG4SField;

    private Decimal2Column[] t3RXXXXG5Field;

    private Decimal2Column[] t3RXXXXG6Field;

    private Ozn2Column[] t3RXXXXG7Field;

    private DGI4nomColumn[] t4RXXXXG1Field;

    private KOATUUColumn[] t4RXXXXG2Field;

    private StrColumn[] t4RXXXXG3SField;

    private Decimal2Column[] t4RXXXXG4Field;

    private Ozn2Column[] t4RXXXXG5Field;

    private DGI4nomColumn[] t5RXXXXG1Field;

    private KOATUUColumn[] t5RXXXXG2Field;

    private StrColumn[] t5RXXXXG3SField;

    private Decimal2Column[] t5RXXXXG4Field;

    private Decimal2Column[] t5RXXXXG5Field;

    private Decimal2Column[] t5RXXXXG6Field;

    private Decimal2Column[] t5RXXXXG7Field;

    private Decimal2Column[] t5RXXXXG8Field;

    private Decimal2Column[] t5RXXXXG9Field;

    private Ozn2Column[] t5RXXXXG10Field;

    private DGI4nomColumn[] t6RXXXXG1Field;

    private KOATUUColumn[] t6RXXXXG2Field;

    private StrColumn[] t6RXXXXG3SField;

    private Decimal2Column[] t6RXXXXG4Field;

    private Decimal2Column[] t6RXXXXG5Field;

    private Decimal2Column[] t6RXXXXG6Field;

    private Decimal2Column[] t6RXXXXG7Field;

    private Ozn2Column[] t6RXXXXG8Field;

    private string hKEXECUTORField;

    private string hEXECUTORField;

    private string hPOSTField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HZ", typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("HZU", typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]

    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public int Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName
    {
        get
        {
            return this.itemElementNameField;
        }
        set
        {
            this.itemElementNameField = value;
        }
    }

    ///// <remarks/>
    //[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    //public string HDATE
    //{
    //    get
    //    {
    //        return this.hDATEField;
    //    }
    //    set
    //    {
    //        this.hDATEField = value;
    //    }
    //}

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "positiveInteger", IsNullable = true)]
    public string HNUM
    {
        get
        {
            return this.hNUMField;
        }
        set
        {
            this.hNUMField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HDATE1
    {
        get
        {
            return this.hDATE1Field;
        }
        set
        {
            this.hDATE1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HTIME1
    {
        get
        {
            return this.hTIME1Field;
        }
        set
        {
            this.hTIME1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HDATE2
    {
        get
        {
            return this.hDATE2Field;
        }
        set
        {
            this.hDATE2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HTIME2
    {
        get
        {
            return this.hTIME2Field;
        }
        set
        {
            this.hTIME2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "positiveInteger", IsNullable = true)]
    public string HNUMREG
    {
        get
        {
            return this.hNUMREGField;
        }
        set
        {
            this.hNUMREGField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HTIN
    {
        get
        {
            return this.hTINField;
        }
        set
        {
            this.hTINField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HNAME
    {
        get
        {
            return this.hNAMEField;
        }
        set
        {
            this.hNAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "positiveInteger")]
    public string R07G1
    {
        get
        {
            return this.r07G1Field;
        }
        set
        {
            this.r07G1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public DGI4nomColumn[] T1RXXXXG1
    {
        get
        {
            return this.t1RXXXXG1Field;
        }
        set
        {
            this.t1RXXXXG1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public KOATUUColumn[] T1RXXXXG2
    {
        get
        {
            return this.t1RXXXXG2Field;
        }
        set
        {
            this.t1RXXXXG2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG3S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T1RXXXXG3S
    {
        get
        {
            return this.t1RXXXXG3SField;
        }
        set
        {
            this.t1RXXXXG3SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG4", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public ChkColumn[] T1RXXXXG4
    {
        get
        {
            return this.t1RXXXXG4Field;
        }
        set
        {
            this.t1RXXXXG4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG5S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T1RXXXXG5S
    {
        get
        {
            return this.t1RXXXXG5SField;
        }
        set
        {
            this.t1RXXXXG5SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG6S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T1RXXXXG6S
    {
        get
        {
            return this.t1RXXXXG6SField;
        }
        set
        {
            this.t1RXXXXG6SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG7", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T1RXXXXG7
    {
        get
        {
            return this.t1RXXXXG7Field;
        }
        set
        {
            this.t1RXXXXG7Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG8", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T1RXXXXG8
    {
        get
        {
            return this.t1RXXXXG8Field;
        }
        set
        {
            this.t1RXXXXG8Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG9", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T1RXXXXG9
    {
        get
        {
            return this.t1RXXXXG9Field;
        }
        set
        {
            this.t1RXXXXG9Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG10", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T1RXXXXG10
    {
        get
        {
            return this.t1RXXXXG10Field;
        }
        set
        {
            this.t1RXXXXG10Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T1RXXXXG11", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Ozn2Column[] T1RXXXXG11
    {
        get
        {
            return this.t1RXXXXG11Field;
        }
        set
        {
            this.t1RXXXXG11Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T2RXXXXG1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public DGI4nomColumn[] T2RXXXXG1
    {
        get
        {
            return this.t2RXXXXG1Field;
        }
        set
        {
            this.t2RXXXXG1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T2RXXXXG2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public KOATUUColumn[] T2RXXXXG2
    {
        get
        {
            return this.t2RXXXXG2Field;
        }
        set
        {
            this.t2RXXXXG2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T2RXXXXG3S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T2RXXXXG3S
    {
        get
        {
            return this.t2RXXXXG3SField;
        }
        set
        {
            this.t2RXXXXG3SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T2RXXXXG4", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T2RXXXXG4
    {
        get
        {
            return this.t2RXXXXG4Field;
        }
        set
        {
            this.t2RXXXXG4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T2RXXXXG5", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T2RXXXXG5
    {
        get
        {
            return this.t2RXXXXG5Field;
        }
        set
        {
            this.t2RXXXXG5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T2RXXXXG6", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Ozn2Column[] T2RXXXXG6
    {
        get
        {
            return this.t2RXXXXG6Field;
        }
        set
        {
            this.t2RXXXXG6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T3RXXXXG1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public DGI4nomColumn[] T3RXXXXG1
    {
        get
        {
            return this.t3RXXXXG1Field;
        }
        set
        {
            this.t3RXXXXG1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T3RXXXXG2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public KOATUUColumn[] T3RXXXXG2
    {
        get
        {
            return this.t3RXXXXG2Field;
        }
        set
        {
            this.t3RXXXXG2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T3RXXXXG3S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T3RXXXXG3S
    {
        get
        {
            return this.t3RXXXXG3SField;
        }
        set
        {
            this.t3RXXXXG3SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T3RXXXXG4S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T3RXXXXG4S
    {
        get
        {
            return this.t3RXXXXG4SField;
        }
        set
        {
            this.t3RXXXXG4SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T3RXXXXG5", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T3RXXXXG5
    {
        get
        {
            return this.t3RXXXXG5Field;
        }
        set
        {
            this.t3RXXXXG5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T3RXXXXG6", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T3RXXXXG6
    {
        get
        {
            return this.t3RXXXXG6Field;
        }
        set
        {
            this.t3RXXXXG6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T3RXXXXG7", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Ozn2Column[] T3RXXXXG7
    {
        get
        {
            return this.t3RXXXXG7Field;
        }
        set
        {
            this.t3RXXXXG7Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T4RXXXXG1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public DGI4nomColumn[] T4RXXXXG1
    {
        get
        {
            return this.t4RXXXXG1Field;
        }
        set
        {
            this.t4RXXXXG1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T4RXXXXG2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public KOATUUColumn[] T4RXXXXG2
    {
        get
        {
            return this.t4RXXXXG2Field;
        }
        set
        {
            this.t4RXXXXG2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T4RXXXXG3S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T4RXXXXG3S
    {
        get
        {
            return this.t4RXXXXG3SField;
        }
        set
        {
            this.t4RXXXXG3SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T4RXXXXG4", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T4RXXXXG4
    {
        get
        {
            return this.t4RXXXXG4Field;
        }
        set
        {
            this.t4RXXXXG4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T4RXXXXG5", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Ozn2Column[] T4RXXXXG5
    {
        get
        {
            return this.t4RXXXXG5Field;
        }
        set
        {
            this.t4RXXXXG5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public DGI4nomColumn[] T5RXXXXG1
    {
        get
        {
            return this.t5RXXXXG1Field;
        }
        set
        {
            this.t5RXXXXG1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public KOATUUColumn[] T5RXXXXG2
    {
        get
        {
            return this.t5RXXXXG2Field;
        }
        set
        {
            this.t5RXXXXG2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG3S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T5RXXXXG3S
    {
        get
        {
            return this.t5RXXXXG3SField;
        }
        set
        {
            this.t5RXXXXG3SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG4", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T5RXXXXG4
    {
        get
        {
            return this.t5RXXXXG4Field;
        }
        set
        {
            this.t5RXXXXG4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG5", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T5RXXXXG5
    {
        get
        {
            return this.t5RXXXXG5Field;
        }
        set
        {
            this.t5RXXXXG5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG6", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T5RXXXXG6
    {
        get
        {
            return this.t5RXXXXG6Field;
        }
        set
        {
            this.t5RXXXXG6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG7", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T5RXXXXG7
    {
        get
        {
            return this.t5RXXXXG7Field;
        }
        set
        {
            this.t5RXXXXG7Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG8", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T5RXXXXG8
    {
        get
        {
            return this.t5RXXXXG8Field;
        }
        set
        {
            this.t5RXXXXG8Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG9", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T5RXXXXG9
    {
        get
        {
            return this.t5RXXXXG9Field;
        }
        set
        {
            this.t5RXXXXG9Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T5RXXXXG10", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Ozn2Column[] T5RXXXXG10
    {
        get
        {
            return this.t5RXXXXG10Field;
        }
        set
        {
            this.t5RXXXXG10Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T6RXXXXG1", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public DGI4nomColumn[] T6RXXXXG1
    {
        get
        {
            return this.t6RXXXXG1Field;
        }
        set
        {
            this.t6RXXXXG1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T6RXXXXG2", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public KOATUUColumn[] T6RXXXXG2
    {
        get
        {
            return this.t6RXXXXG2Field;
        }
        set
        {
            this.t6RXXXXG2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T6RXXXXG3S", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public StrColumn[] T6RXXXXG3S
    {
        get
        {
            return this.t6RXXXXG3SField;
        }
        set
        {
            this.t6RXXXXG3SField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T6RXXXXG4", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T6RXXXXG4
    {
        get
        {
            return this.t6RXXXXG4Field;
        }
        set
        {
            this.t6RXXXXG4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T6RXXXXG5", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T6RXXXXG5
    {
        get
        {
            return this.t6RXXXXG5Field;
        }
        set
        {
            this.t6RXXXXG5Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T6RXXXXG6", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T6RXXXXG6
    {
        get
        {
            return this.t6RXXXXG6Field;
        }
        set
        {
            this.t6RXXXXG6Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T6RXXXXG7", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Decimal2Column[] T6RXXXXG7
    {
        get
        {
            return this.t6RXXXXG7Field;
        }
        set
        {
            this.t6RXXXXG7Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("T6RXXXXG8", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
    public Ozn2Column[] T6RXXXXG8
    {
        get
        {
            return this.t6RXXXXG8Field;
        }
        set
        {
            this.t6RXXXXG8Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HKEXECUTOR
    {
        get
        {
            return this.hKEXECUTORField;
        }
        set
        {
            this.hKEXECUTORField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HEXECUTOR
    {
        get
        {
            return this.hEXECUTORField;
        }
        set
        {
            this.hEXECUTORField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HPOST
    {
        get
        {
            return this.hPOSTField;
        }
        set
        {
            this.hPOSTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
public enum ItemChoiceType
{

    /// <remarks/>
    HZ,

    /// <remarks/>
    HZU,
}
